[package]
name = "eval"
version = "0.1.0"
description = "Expression evaluator"
keywords = ["expression", "evaluate", "evaluator", "expr"]
authors = ["fengcen <fengcen.love@gmail.com>"]
repository = "https://github.com/fengcen/eval.git"
homepage = "https://github.com/fengcen/eval"
documentation = "https://github.com/fengcen/eval"
readme = "README.md"
license = "MIT"

[lib]
name = "eval"
path = "src/lib.rs"

[dependencies]
serde_json = "^0.8"
quick-error = "^1.1"
