[package]
name = "evalexpr"
version = "1.1.0"
description = "A powerful arithmetic and boolean expression evaluator"
keywords = ["expression", "evaluate", "evaluator", "arithmetic", "boolean"]
categories = ["parsing", "game-engines"]
authors = ["isibboi <isibboi@gmail.com>"]
repository = "https://github.com/ISibboI/evalexpr.git"
homepage = "https://github.com/ISibboI/evalexpr"
documentation = "https://docs.rs/evalexpr"
readme = "README.md"
license = "MIT"

[lib]
name = "evalexpr"
path = "src/lib.rs"

[dependencies]

[features]
