[package]
name = "evalexpr"
version = "0.4.4"
description = "Expression evaluator"
keywords = ["expression", "evaluate", "evaluator", "expr", "template"]
authors = ["fengcen <fengcen.love@gmail.com>", "isibboi <isibboi@gmail.com>"]
repository = "https://github.com/ISibboI/eval.git"
homepage = "https://github.com/ISibboI/eval"
documentation = "https://docs.rs/evalexpr"
readme = "README.md"
license = "MIT"

[lib]
name = "evalexpr"
path = "src/lib.rs"

[dependencies]
serde = ">= 0.9, < 2"
serde_json = ">= 0.9, < 2"
quick-error = "^1.1"

[features]
unstable = []
